### ISSUE TITLE
Not working with `npm i -D cli-typescript-class-organizer`

### ISSUE THREAD

**Issue by thanhhoa214** [vvscode/cli-typescript-class-organizer#1]
Hi thanks for your contribution 👍
   
   I installed it with `npm i -D cli-typescript-class-organizer` for own strategy. 
   Then, run it from package.json with `"tsco" : "tsco --help"` but seem to be not working and throw this error. 
   Please help.

```
Error: Cannot find module '/Users/data/projects/click-ui/index.ts'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at Object.<anonymous> (/Users/data/projects/click-ui/node_modules/ts-node/src/bin.ts:157:12)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

**Comment by vvscode** [comment]
@thanhhoa214  thanks a lot for your feedback

Please try the latest version `0.0.6`

if the issue is still actual for you - feel free to reopen this issue with further details

Keep safe
